-- WARNING: This schema excerpt is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_action_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action_type text NOT NULL,
  intent text,
  user_message text,
  execution_plan jsonb,
  tools_used ARRAY,
  action_details jsonb DEFAULT '{}'::jsonb,
  results jsonb,
  success boolean DEFAULT true,
  error_message text,
  cost_usd numeric,
  execution_time_ms integer,
  approved_at timestamp with time zone,
  executed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_action_log_pkey PRIMARY KEY (id),
  CONSTRAINT ai_action_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  suburb text NOT NULL,
  service text NOT NULL,
  message text,
  urgency text,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'quoted'::text, 'converted'::text, 'lost'::text])),
  source text DEFAULT 'website'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  ai_score integer CHECK (ai_score >= 0 AND ai_score <= 10),
  ai_tags jsonb DEFAULT '[]'::jsonb,
  service_area_match boolean,
  auto_enriched_at timestamp with time zone,
  merged_into_lead_id uuid,
  merge_status text DEFAULT 'active'::text,
  merge_history jsonb DEFAULT '[]'::jsonb,
  notion_sync_id text,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_merged_into_lead_id_fkey FOREIGN KEY (merged_into_lead_id) REFERENCES public.leads(id)
);

CREATE TABLE public.content_gallery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  image_url text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['before'::text, 'after'::text, 'progress'::text, 'general'::text])),
  pair_id text,
  job_type text,
  suburb text,
  featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  case_study_id uuid,
  notion_id text,
  last_synced_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  meta_title text,
  meta_description text,
  CONSTRAINT content_gallery_pkey PRIMARY KEY (id),
  CONSTRAINT content_gallery_case_study_id_fkey FOREIGN KEY (case_study_id) REFERENCES public.content_case_studies(id)
);

CREATE TABLE public.media_gallery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title text NOT NULL,
  description text,
  image_url text NOT NULL,
  thumbnail_url text,
  category text,
  tags ARRAY,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  show_on_homepage boolean DEFAULT false,
  show_on_about boolean DEFAULT false,
  show_on_services boolean DEFAULT false,
  show_on_portfolio boolean DEFAULT false,
  CONSTRAINT media_gallery_pkey PRIMARY KEY (id)
);

CREATE TABLE public.pricing_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id text NOT NULL UNIQUE,
  item_name text NOT NULL,
  item_category text NOT NULL,
  unit_of_measure text NOT NULL,
  base_cost numeric NOT NULL,
  preferred_supplier text,
  supplier_code text,
  usage_notes text,
  quality_tier text,
  version_history jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  embedding USER-DEFINED,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pricing_items_pkey PRIMARY KEY (id)
);

CREATE TABLE public.pricing_constants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  constant_id text NOT NULL UNIQUE,
  material_markup numeric NOT NULL DEFAULT 0.20,
  contingency numeric NOT NULL DEFAULT 0.05,
  profit_margin numeric NOT NULL DEFAULT 0.30,
  gst numeric NOT NULL DEFAULT 0.10,
  description text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pricing_constants_pkey PRIMARY KEY (id)
);

CREATE TABLE public.roof_measurements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  total_area_m2 numeric NOT NULL,
  predominant_pitch numeric,
  roof_segments jsonb DEFAULT '[]'::jsonb,
  perimeter_features jsonb DEFAULT '[]'::jsonb,
  hips jsonb DEFAULT '[]'::jsonb,
  ridges jsonb DEFAULT '[]'::jsonb,
  valleys jsonb DEFAULT '[]'::jsonb,
  imagery_url text,
  imagery_date date,
  imagery_quality text,
  solar_panel_capacity_watts integer,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  linked_quote_id uuid,
  linked_lead_id uuid,
  linked_inspection_id uuid,
  CONSTRAINT roof_measurements_pkey PRIMARY KEY (id),
  CONSTRAINT roof_measurements_linked_inspection_id_fkey FOREIGN KEY (linked_inspection_id) REFERENCES public.inspection_reports(id),
  CONSTRAINT roof_measurements_linked_lead_id_fkey FOREIGN KEY (linked_lead_id) REFERENCES public.leads(id),
  CONSTRAINT roof_measurements_linked_quote_id_fkey FOREIGN KEY (linked_quote_id) REFERENCES public.quotes(id)
);

CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inspection_report_id uuid,
  quote_number text NOT NULL UNIQUE,
  client_name text NOT NULL,
  site_address text NOT NULL,
  suburb_postcode text NOT NULL,
  email text,
  phone text NOT NULL,
  tier_level text NOT NULL CHECK (tier_level = ANY (ARRAY['essential'::text, 'premium'::text, 'complete'::text])),
  subtotal numeric NOT NULL,
  gst numeric NOT NULL,
  total numeric NOT NULL,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'approved'::text, 'rejected'::text, 'completed'::text])),
  valid_until date,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pricing_version text,
  pricing_hash text,
  pricing_snapshot jsonb,
  regional_modifier numeric DEFAULT 1.0,
  tier_profile text CHECK (tier_profile = ANY (ARRAY['REPAIR'::text, 'RESTORE'::text, 'PREMIUM'::text])),
  scope jsonb DEFAULT '[]'::jsonb,
  line_items jsonb DEFAULT '[]'::jsonb,
  photo_ids ARRAY DEFAULT '{}'::text[],
  pricing jsonb DEFAULT '{}'::jsonb,
  terms jsonb DEFAULT '{}'::jsonb,
  version integer DEFAULT 1,
  parent_quote_id uuid,
  sent_at timestamp with time zone,
  accepted_at timestamp with time zone,
  discount_amount numeric DEFAULT 0,
  discount_reason text,
  draft boolean DEFAULT true,
  notion_sync_id text,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT quotes_inspection_report_id_fkey FOREIGN KEY (inspection_report_id) REFERENCES public.inspection_reports(id),
  CONSTRAINT quotes_parent_quote_id_fkey FOREIGN KEY (parent_quote_id) REFERENCES public.quotes(id)
);

CREATE TABLE public.quote_line_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  service_item text NOT NULL,
  description text,
  quantity numeric NOT NULL,
  unit text NOT NULL,
  unit_rate numeric NOT NULL,
  line_total numeric NOT NULL,
  material_spec_id uuid,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  service_code text,
  composition jsonb,
  warranty_years ARRAY,
  material_spec text,
  CONSTRAINT quote_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_line_items_material_spec_id_fkey FOREIGN KEY (material_spec_id) REFERENCES public.material_specs(id),
  CONSTRAINT quote_line_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
