name: MKF unzip to Pages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. mkf-v1.0)"
        required: true
        default: mkf-v1.0

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Download ZIP assets for tag
        uses: robinraju/release-downloader@v1.9
        with:
          repository: ${{ github.repository }}
          tag: ${{ inputs.tag }}
          fileName: "*.zip"
          out-file-path: _mkf
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if no ZIPs
        run: |
          shopt -s nullglob
          z=( _mkf/*.zip )
          echo "Found ${#z[@]} zip(s)"
          [ ${#z[@]} -gt 0 ] || { echo "No *.zip assets on that tag"; exit 1; }

      - name: Unzip into docs/mkf/<tag>/
        run: |
          set -e
          TARGET="docs/mkf/${{ inputs.tag }}"
          mkdir -p "$TARGET"
          for z in _mkf/*.zip; do
            echo "Unzipping $z -> $TARGET"
            unzip -o "$z" -d "$TARGET"
          done
          touch docs/.nojekyll

      - name: Commit extracted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(mkf): extract ${{ inputs.tag }} to docs/"
